//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace convert
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bpm03.bes.com.tw/", ConfigurationName="convert.ConvertFileSoap")]
    public interface ConvertFileSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/WordByteToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<convert.WordByteToPDFByteResponse> WordByteToPDFByteAsync(convert.WordByteToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/WordFileToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<convert.WordFileToPDFByteResponse> WordFileToPDFByteAsync(convert.WordFileToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/UploadWordToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<convert.UploadWordToPDFByteResponse> UploadWordToPDFByteAsync(convert.UploadWordToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/StreamWordToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.StreamWordToPDFByteResponse> StreamWordToPDFByteAsync(convert.StreamWordToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/MStreamWordToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.MStreamWordToPDFByteResponse> MStreamWordToPDFByteAsync(convert.MStreamWordToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/WordByteToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.WordByteToPDFFileResponse> WordByteToPDFFileAsync(convert.WordByteToPDFFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/WordFileToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task WordFileToPDFFileAsync(string filePath, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/StreamWordToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task StreamWordToPDFFileAsync(convert.FileStream file, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/MStreamWordToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task MStreamWordToPDFFileAsync(convert.MemoryStream ms, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/UploadWordToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task UploadWordToPDFFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/ExcelByteToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.ExcelByteToPDFByteResponse> ExcelByteToPDFByteAsync(convert.ExcelByteToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/ExcelFileToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.ExcelFileToPDFByteResponse> ExcelFileToPDFByteAsync(convert.ExcelFileToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/UploadExcelToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.UploadExcelToPDFByteResponse> UploadExcelToPDFByteAsync(convert.UploadExcelToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/StreamExcelToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.StreamExcelToPDFByteResponse> StreamExcelToPDFByteAsync(convert.StreamExcelToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/MStreamExcelToPDFByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.MStreamExcelToPDFByteResponse> MStreamExcelToPDFByteAsync(convert.MStreamExcelToPDFByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/ExcelByteToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.ExcelByteToPDFFileResponse> ExcelByteToPDFFileAsync(convert.ExcelByteToPDFFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/ExcelFileToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task ExcelFileToPDFFileAsync(string filePath, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/StreamExcelToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task StreamExcelToPDFFileAsync(convert.FileStream file, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/MStreamExcelToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task MStreamExcelToPDFFileAsync(convert.MemoryStream ms, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/UploadExcelToPDFFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task UploadExcelToPDFFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/PDFFileMergeToByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.PDFFileMergeToByteResponse> PDFFileMergeToByteAsync(convert.PDFFileMergeToByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/PDFByteMergeToByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.PDFByteMergeToByteResponse> PDFByteMergeToByteAsync(convert.PDFByteMergeToByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/UploadPDFMergeToByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<convert.UploadPDFMergeToByteResponse> UploadPDFMergeToByteAsync(convert.UploadPDFMergeToByteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/PDFFileMergeToFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task PDFFileMergeToFileAsync(string[] filePaths, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/PDFByteMergeToFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task PDFByteMergeToFileAsync(byte[][] files, string pdfPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpm03.bes.com.tw/UploadPDFMergeToFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task UploadPDFMergeToFileAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WordByteToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class WordByteToPDFByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public WordByteToPDFByteRequest()
        {
        }
        
        public WordByteToPDFByteRequest(byte[] file)
        {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WordByteToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class WordByteToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] WordByteToPDFByteResult;
        
        public WordByteToPDFByteResponse()
        {
        }
        
        public WordByteToPDFByteResponse(byte[] WordByteToPDFByteResult)
        {
            this.WordByteToPDFByteResult = WordByteToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WordFileToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class WordFileToPDFByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        public string filePath;
        
        public WordFileToPDFByteRequest()
        {
        }
        
        public WordFileToPDFByteRequest(string filePath)
        {
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WordFileToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class WordFileToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] WordFileToPDFByteResult;
        
        public WordFileToPDFByteResponse()
        {
        }
        
        public WordFileToPDFByteResponse(byte[] WordFileToPDFByteResult)
        {
            this.WordFileToPDFByteResult = WordFileToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadWordToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class UploadWordToPDFByteRequest
    {
        
        public UploadWordToPDFByteRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadWordToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class UploadWordToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UploadWordToPDFByteResult;
        
        public UploadWordToPDFByteResponse()
        {
        }
        
        public UploadWordToPDFByteResponse(byte[] UploadWordToPDFByteResult)
        {
            this.UploadWordToPDFByteResult = UploadWordToPDFByteResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bpm03.bes.com.tw/")]
    public partial class FileStream : Stream
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MemoryStream))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileStream))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bpm03.bes.com.tw/")]
    public abstract partial class Stream : MarshalByRefObject
    {
        
        private long positionField;
        
        private int readTimeoutField;
        
        private int writeTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ReadTimeout
        {
            get
            {
                return this.readTimeoutField;
            }
            set
            {
                this.readTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int WriteTimeout
        {
            get
            {
                return this.writeTimeoutField;
            }
            set
            {
                this.writeTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Stream))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MemoryStream))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileStream))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bpm03.bes.com.tw/")]
    public abstract partial class MarshalByRefObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bpm03.bes.com.tw/")]
    public partial class MemoryStream : Stream
    {
        
        private int capacityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StreamWordToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class StreamWordToPDFByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        public convert.FileStream file;
        
        public StreamWordToPDFByteRequest()
        {
        }
        
        public StreamWordToPDFByteRequest(convert.FileStream file)
        {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StreamWordToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class StreamWordToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] StreamWordToPDFByteResult;
        
        public StreamWordToPDFByteResponse()
        {
        }
        
        public StreamWordToPDFByteResponse(byte[] StreamWordToPDFByteResult)
        {
            this.StreamWordToPDFByteResult = StreamWordToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MStreamWordToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class MStreamWordToPDFByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        public convert.MemoryStream ms;
        
        public MStreamWordToPDFByteRequest()
        {
        }
        
        public MStreamWordToPDFByteRequest(convert.MemoryStream ms)
        {
            this.ms = ms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MStreamWordToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class MStreamWordToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MStreamWordToPDFByteResult;
        
        public MStreamWordToPDFByteResponse()
        {
        }
        
        public MStreamWordToPDFByteResponse(byte[] MStreamWordToPDFByteResult)
        {
            this.MStreamWordToPDFByteResult = MStreamWordToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WordByteToPDFFile", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class WordByteToPDFFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=1)]
        public string pdfPath;
        
        public WordByteToPDFFileRequest()
        {
        }
        
        public WordByteToPDFFileRequest(byte[] file, string pdfPath)
        {
            this.file = file;
            this.pdfPath = pdfPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WordByteToPDFFileResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class WordByteToPDFFileResponse
    {
        
        public WordByteToPDFFileResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcelByteToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class ExcelByteToPDFByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public ExcelByteToPDFByteRequest()
        {
        }
        
        public ExcelByteToPDFByteRequest(byte[] file)
        {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcelByteToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class ExcelByteToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExcelByteToPDFByteResult;
        
        public ExcelByteToPDFByteResponse()
        {
        }
        
        public ExcelByteToPDFByteResponse(byte[] ExcelByteToPDFByteResult)
        {
            this.ExcelByteToPDFByteResult = ExcelByteToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcelFileToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class ExcelFileToPDFByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        public string filePath;
        
        public ExcelFileToPDFByteRequest()
        {
        }
        
        public ExcelFileToPDFByteRequest(string filePath)
        {
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcelFileToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class ExcelFileToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExcelFileToPDFByteResult;
        
        public ExcelFileToPDFByteResponse()
        {
        }
        
        public ExcelFileToPDFByteResponse(byte[] ExcelFileToPDFByteResult)
        {
            this.ExcelFileToPDFByteResult = ExcelFileToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadExcelToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class UploadExcelToPDFByteRequest
    {
        
        public UploadExcelToPDFByteRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadExcelToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class UploadExcelToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UploadExcelToPDFByteResult;
        
        public UploadExcelToPDFByteResponse()
        {
        }
        
        public UploadExcelToPDFByteResponse(byte[] UploadExcelToPDFByteResult)
        {
            this.UploadExcelToPDFByteResult = UploadExcelToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StreamExcelToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class StreamExcelToPDFByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        public convert.FileStream file;
        
        public StreamExcelToPDFByteRequest()
        {
        }
        
        public StreamExcelToPDFByteRequest(convert.FileStream file)
        {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StreamExcelToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class StreamExcelToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] StreamExcelToPDFByteResult;
        
        public StreamExcelToPDFByteResponse()
        {
        }
        
        public StreamExcelToPDFByteResponse(byte[] StreamExcelToPDFByteResult)
        {
            this.StreamExcelToPDFByteResult = StreamExcelToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MStreamExcelToPDFByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class MStreamExcelToPDFByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        public convert.MemoryStream ms;
        
        public MStreamExcelToPDFByteRequest()
        {
        }
        
        public MStreamExcelToPDFByteRequest(convert.MemoryStream ms)
        {
            this.ms = ms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MStreamExcelToPDFByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class MStreamExcelToPDFByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MStreamExcelToPDFByteResult;
        
        public MStreamExcelToPDFByteResponse()
        {
        }
        
        public MStreamExcelToPDFByteResponse(byte[] MStreamExcelToPDFByteResult)
        {
            this.MStreamExcelToPDFByteResult = MStreamExcelToPDFByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcelByteToPDFFile", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class ExcelByteToPDFFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=1)]
        public string pdfPath;
        
        public ExcelByteToPDFFileRequest()
        {
        }
        
        public ExcelByteToPDFFileRequest(byte[] file, string pdfPath)
        {
            this.file = file;
            this.pdfPath = pdfPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcelByteToPDFFileResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class ExcelByteToPDFFileResponse
    {
        
        public ExcelByteToPDFFileResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PDFFileMergeToByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class PDFFileMergeToByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        public string[] filePaths;
        
        public PDFFileMergeToByteRequest()
        {
        }
        
        public PDFFileMergeToByteRequest(string[] filePaths)
        {
            this.filePaths = filePaths;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PDFFileMergeToByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class PDFFileMergeToByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PDFFileMergeToByteResult;
        
        public PDFFileMergeToByteResponse()
        {
        }
        
        public PDFFileMergeToByteResponse(byte[] PDFFileMergeToByteResult)
        {
            this.PDFFileMergeToByteResult = PDFFileMergeToByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PDFByteMergeToByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class PDFByteMergeToByteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        public byte[][] files;
        
        public PDFByteMergeToByteRequest()
        {
        }
        
        public PDFByteMergeToByteRequest(byte[][] files)
        {
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PDFByteMergeToByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class PDFByteMergeToByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PDFByteMergeToByteResult;
        
        public PDFByteMergeToByteResponse()
        {
        }
        
        public PDFByteMergeToByteResponse(byte[] PDFByteMergeToByteResult)
        {
            this.PDFByteMergeToByteResult = PDFByteMergeToByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadPDFMergeToByte", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class UploadPDFMergeToByteRequest
    {
        
        public UploadPDFMergeToByteRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadPDFMergeToByteResponse", WrapperNamespace="http://bpm03.bes.com.tw/", IsWrapped=true)]
    public partial class UploadPDFMergeToByteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpm03.bes.com.tw/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UploadPDFMergeToByteResult;
        
        public UploadPDFMergeToByteResponse()
        {
        }
        
        public UploadPDFMergeToByteResponse(byte[] UploadPDFMergeToByteResult)
        {
            this.UploadPDFMergeToByteResult = UploadPDFMergeToByteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ConvertFileSoapChannel : convert.ConvertFileSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ConvertFileSoapClient : System.ServiceModel.ClientBase<convert.ConvertFileSoap>, convert.ConvertFileSoap
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConvertFileSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ConvertFileSoapClient.GetBindingForEndpoint(endpointConfiguration), ConvertFileSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConvertFileSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConvertFileSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConvertFileSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConvertFileSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConvertFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.WordByteToPDFByteResponse> convert.ConvertFileSoap.WordByteToPDFByteAsync(convert.WordByteToPDFByteRequest request)
        {
            return base.Channel.WordByteToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.WordByteToPDFByteResponse> WordByteToPDFByteAsync(byte[] file)
        {
            convert.WordByteToPDFByteRequest inValue = new convert.WordByteToPDFByteRequest();
            inValue.file = file;
            return ((convert.ConvertFileSoap)(this)).WordByteToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.WordFileToPDFByteResponse> convert.ConvertFileSoap.WordFileToPDFByteAsync(convert.WordFileToPDFByteRequest request)
        {
            return base.Channel.WordFileToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.WordFileToPDFByteResponse> WordFileToPDFByteAsync(string filePath)
        {
            convert.WordFileToPDFByteRequest inValue = new convert.WordFileToPDFByteRequest();
            inValue.filePath = filePath;
            return ((convert.ConvertFileSoap)(this)).WordFileToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.UploadWordToPDFByteResponse> convert.ConvertFileSoap.UploadWordToPDFByteAsync(convert.UploadWordToPDFByteRequest request)
        {
            return base.Channel.UploadWordToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.UploadWordToPDFByteResponse> UploadWordToPDFByteAsync()
        {
            convert.UploadWordToPDFByteRequest inValue = new convert.UploadWordToPDFByteRequest();
            return ((convert.ConvertFileSoap)(this)).UploadWordToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.StreamWordToPDFByteResponse> convert.ConvertFileSoap.StreamWordToPDFByteAsync(convert.StreamWordToPDFByteRequest request)
        {
            return base.Channel.StreamWordToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.StreamWordToPDFByteResponse> StreamWordToPDFByteAsync(convert.FileStream file)
        {
            convert.StreamWordToPDFByteRequest inValue = new convert.StreamWordToPDFByteRequest();
            inValue.file = file;
            return ((convert.ConvertFileSoap)(this)).StreamWordToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.MStreamWordToPDFByteResponse> convert.ConvertFileSoap.MStreamWordToPDFByteAsync(convert.MStreamWordToPDFByteRequest request)
        {
            return base.Channel.MStreamWordToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.MStreamWordToPDFByteResponse> MStreamWordToPDFByteAsync(convert.MemoryStream ms)
        {
            convert.MStreamWordToPDFByteRequest inValue = new convert.MStreamWordToPDFByteRequest();
            inValue.ms = ms;
            return ((convert.ConvertFileSoap)(this)).MStreamWordToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.WordByteToPDFFileResponse> convert.ConvertFileSoap.WordByteToPDFFileAsync(convert.WordByteToPDFFileRequest request)
        {
            return base.Channel.WordByteToPDFFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.WordByteToPDFFileResponse> WordByteToPDFFileAsync(byte[] file, string pdfPath)
        {
            convert.WordByteToPDFFileRequest inValue = new convert.WordByteToPDFFileRequest();
            inValue.file = file;
            inValue.pdfPath = pdfPath;
            return ((convert.ConvertFileSoap)(this)).WordByteToPDFFileAsync(inValue);
        }
        
        public System.Threading.Tasks.Task WordFileToPDFFileAsync(string filePath, string pdfPath)
        {
            return base.Channel.WordFileToPDFFileAsync(filePath, pdfPath);
        }
        
        public System.Threading.Tasks.Task StreamWordToPDFFileAsync(convert.FileStream file, string pdfPath)
        {
            return base.Channel.StreamWordToPDFFileAsync(file, pdfPath);
        }
        
        public System.Threading.Tasks.Task MStreamWordToPDFFileAsync(convert.MemoryStream ms, string pdfPath)
        {
            return base.Channel.MStreamWordToPDFFileAsync(ms, pdfPath);
        }
        
        public System.Threading.Tasks.Task UploadWordToPDFFileAsync()
        {
            return base.Channel.UploadWordToPDFFileAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.ExcelByteToPDFByteResponse> convert.ConvertFileSoap.ExcelByteToPDFByteAsync(convert.ExcelByteToPDFByteRequest request)
        {
            return base.Channel.ExcelByteToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.ExcelByteToPDFByteResponse> ExcelByteToPDFByteAsync(byte[] file)
        {
            convert.ExcelByteToPDFByteRequest inValue = new convert.ExcelByteToPDFByteRequest();
            inValue.file = file;
            return ((convert.ConvertFileSoap)(this)).ExcelByteToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.ExcelFileToPDFByteResponse> convert.ConvertFileSoap.ExcelFileToPDFByteAsync(convert.ExcelFileToPDFByteRequest request)
        {
            return base.Channel.ExcelFileToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.ExcelFileToPDFByteResponse> ExcelFileToPDFByteAsync(string filePath)
        {
            convert.ExcelFileToPDFByteRequest inValue = new convert.ExcelFileToPDFByteRequest();
            inValue.filePath = filePath;
            return ((convert.ConvertFileSoap)(this)).ExcelFileToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.UploadExcelToPDFByteResponse> convert.ConvertFileSoap.UploadExcelToPDFByteAsync(convert.UploadExcelToPDFByteRequest request)
        {
            return base.Channel.UploadExcelToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.UploadExcelToPDFByteResponse> UploadExcelToPDFByteAsync()
        {
            convert.UploadExcelToPDFByteRequest inValue = new convert.UploadExcelToPDFByteRequest();
            return ((convert.ConvertFileSoap)(this)).UploadExcelToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.StreamExcelToPDFByteResponse> convert.ConvertFileSoap.StreamExcelToPDFByteAsync(convert.StreamExcelToPDFByteRequest request)
        {
            return base.Channel.StreamExcelToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.StreamExcelToPDFByteResponse> StreamExcelToPDFByteAsync(convert.FileStream file)
        {
            convert.StreamExcelToPDFByteRequest inValue = new convert.StreamExcelToPDFByteRequest();
            inValue.file = file;
            return ((convert.ConvertFileSoap)(this)).StreamExcelToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.MStreamExcelToPDFByteResponse> convert.ConvertFileSoap.MStreamExcelToPDFByteAsync(convert.MStreamExcelToPDFByteRequest request)
        {
            return base.Channel.MStreamExcelToPDFByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.MStreamExcelToPDFByteResponse> MStreamExcelToPDFByteAsync(convert.MemoryStream ms)
        {
            convert.MStreamExcelToPDFByteRequest inValue = new convert.MStreamExcelToPDFByteRequest();
            inValue.ms = ms;
            return ((convert.ConvertFileSoap)(this)).MStreamExcelToPDFByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.ExcelByteToPDFFileResponse> convert.ConvertFileSoap.ExcelByteToPDFFileAsync(convert.ExcelByteToPDFFileRequest request)
        {
            return base.Channel.ExcelByteToPDFFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.ExcelByteToPDFFileResponse> ExcelByteToPDFFileAsync(byte[] file, string pdfPath)
        {
            convert.ExcelByteToPDFFileRequest inValue = new convert.ExcelByteToPDFFileRequest();
            inValue.file = file;
            inValue.pdfPath = pdfPath;
            return ((convert.ConvertFileSoap)(this)).ExcelByteToPDFFileAsync(inValue);
        }
        
        public System.Threading.Tasks.Task ExcelFileToPDFFileAsync(string filePath, string pdfPath)
        {
            return base.Channel.ExcelFileToPDFFileAsync(filePath, pdfPath);
        }
        
        public System.Threading.Tasks.Task StreamExcelToPDFFileAsync(convert.FileStream file, string pdfPath)
        {
            return base.Channel.StreamExcelToPDFFileAsync(file, pdfPath);
        }
        
        public System.Threading.Tasks.Task MStreamExcelToPDFFileAsync(convert.MemoryStream ms, string pdfPath)
        {
            return base.Channel.MStreamExcelToPDFFileAsync(ms, pdfPath);
        }
        
        public System.Threading.Tasks.Task UploadExcelToPDFFileAsync()
        {
            return base.Channel.UploadExcelToPDFFileAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.PDFFileMergeToByteResponse> convert.ConvertFileSoap.PDFFileMergeToByteAsync(convert.PDFFileMergeToByteRequest request)
        {
            return base.Channel.PDFFileMergeToByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.PDFFileMergeToByteResponse> PDFFileMergeToByteAsync(string[] filePaths)
        {
            convert.PDFFileMergeToByteRequest inValue = new convert.PDFFileMergeToByteRequest();
            inValue.filePaths = filePaths;
            return ((convert.ConvertFileSoap)(this)).PDFFileMergeToByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.PDFByteMergeToByteResponse> convert.ConvertFileSoap.PDFByteMergeToByteAsync(convert.PDFByteMergeToByteRequest request)
        {
            return base.Channel.PDFByteMergeToByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.PDFByteMergeToByteResponse> PDFByteMergeToByteAsync(byte[][] files)
        {
            convert.PDFByteMergeToByteRequest inValue = new convert.PDFByteMergeToByteRequest();
            inValue.files = files;
            return ((convert.ConvertFileSoap)(this)).PDFByteMergeToByteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<convert.UploadPDFMergeToByteResponse> convert.ConvertFileSoap.UploadPDFMergeToByteAsync(convert.UploadPDFMergeToByteRequest request)
        {
            return base.Channel.UploadPDFMergeToByteAsync(request);
        }
        
        public System.Threading.Tasks.Task<convert.UploadPDFMergeToByteResponse> UploadPDFMergeToByteAsync()
        {
            convert.UploadPDFMergeToByteRequest inValue = new convert.UploadPDFMergeToByteRequest();
            return ((convert.ConvertFileSoap)(this)).UploadPDFMergeToByteAsync(inValue);
        }
        
        public System.Threading.Tasks.Task PDFFileMergeToFileAsync(string[] filePaths, string pdfPath)
        {
            return base.Channel.PDFFileMergeToFileAsync(filePaths, pdfPath);
        }
        
        public System.Threading.Tasks.Task PDFByteMergeToFileAsync(byte[][] files, string pdfPath)
        {
            return base.Channel.PDFByteMergeToFileAsync(files, pdfPath);
        }
        
        public System.Threading.Tasks.Task UploadPDFMergeToFileAsync()
        {
            return base.Channel.UploadPDFMergeToFileAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConvertFileSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ConvertFileSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConvertFileSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://besapi.bes.com.tw:8071/ConvertFile.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ConvertFileSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://besapi.bes.com.tw:8071/ConvertFile.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ConvertFileSoap,
            
            ConvertFileSoap12,
        }
    }
}
